DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS attributes;

CREATE TABLE attributes (
  show_id INTEGER PRIMARY KEY AUTOINCREMENT,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  director TEXT NOT NULL,
  cast TEXT NOT NULL,
  country TEXT NOT NULL,
  date_added TEXT NOT NULL,
  release_year TEXT NOT NULL,
  rating TEXT NOT NULL,
  duration TEXT NOT NULL,
  listed_in TEXT NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE review (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  author_id INTEGER NOT NULL,
  content TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
